---
title: "enfr 2018 survey"
author: "Victoria ODonnell"
date: "November 19, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survey)

```


Abro la base ENFR 2018 y la base de las réplicas de bootstrapeo

```{r}

enfr2018 <- read.table("C:/Users/Ale/Desktop/Curso ciencia de datos/Nueva carpeta/ENFR 2018 - Base usuario.txt", header = T, sep = "|")

dim(enfr2018)
glimpse(enfr2018)
head(enfr2018)

## le saco las variables de ponderacion porque voy a unir la base de replicas asi que si no las voy a tener duplicadas. Si no voy a usar intervalos entonces este paso no es necesario


enfr2018 <- enfr2018 %>% 
  select(-c(wf1p, wf2p, wf3p))

enfr2018rep <- read.table("C:/Users/Ale/Desktop/Curso ciencia de datos/Nueva carpeta/ENFR 2018 - Base de replicas.txt", header = T, sep = "|")

dim(enfr2018rep)
glimpse(enfr2018rep)
head(enfr2018rep)




```



Uno ambas bases por la columna ID


```{r}

enfr2018 <- enfr2018 %>% 
  left_join(enfr2018rep, by = "id")

```



Determino el disenio de muestreo de la encuesta (polietapico con intervalos por bootstrap)

```{r}

diseno1 <- svrepdesign(data = enfr2018, 
                       weights = ~wf1p,
                       repweights = "wf1p_rep[1-9]+",
                       type = "bootstrap",
                       mse = T)

# diseno2 <- svrepdesign(data = enfr2018, 
#                        weights = ~wf2p,
#                        repweights = "wf2p_rep[1-9]+",
#                        type = "bootstrap",
#                        mse = T)
# 
# diseno3 <- svrepdesign(data = enfr2018, 
#                        weights = ~wf3p,
#                        repweights = "wf3p_rep[1-9]+",
#                        type = "bootstrap",
#                        mse = T)


```


Analisis univariado

```{r}

confint(svymean(~I(consumo_tabaco_100 == 1), design = diseno1, df=degf(diseno1), level = 0.95))



tabaco <- svyciprop(~I(mamo== 1), design=diseno1 , na.rm = T)
tabaco


ene <- enfr2018 %>% filter(consumo_tabaco_100 == 1) %>% nrow()
ene

```



Regresiones con plan de analisis 

```{r}

tabaco_reg <- svyglm(consumo_tabaco_100~rango_edad + nivel_instruccion + quintil_uc + bhch03, design=diseno1)
summary(tabaco_reg)


```





Tablas y metricas bivariadas

```{r}
 cobertura <- svyby(~as.factor(consumo_tabaco_100 == 1), ~as.factor(cobertura_salud), diseno1, svymean, vartype="ci", method="beta", na.rm = T, df=degf(diseno1), level = 0.95)

  cv_cob <- cv(svyby(~as.factor(consumo_tabaco_100 == 1), ~as.factor(cobertura_salud), diseno1, svymean, method="beta", na.rm = T, df=degf(diseno1), level = 0.95))
  
  
  pond_cob <- svyby(~as.factor(consumo_tabaco_100 == 1), ~as.factor(cobertura_salud), diseno1, unwtd.count, vartype="ci", method="beta", na.rm = T, df=degf(diseno1), level = 0.95)
  

    tot_cob <- svyby(~as.factor(consumo_tabaco_100 == 1), ~as.factor(cobertura_salud), diseno1, unwtd.count, vartype="ci", method="beta", na.rm = T, df=degf(diseno3), level = 0.95)
    

cobertura_chequeo <- as.data.frame(cbind(valores = cobertura[,1],
                                estimador = round(cobertura[,3]*100,1),
                               li = round(cobertura[,5]*100,1),
                               ls = round(cobertura[,7]*100,1),
                                 cv = round(cv_cob$se1*100, 1), 
                               pond = pond_cob$counts, 
                               tot = tot_cob$counts,
                               indicador = "cobertura"))
   
```



